import {clamp,contrastRatio} from './color.js';
export const STORAGE_KEY='design-theory-playground-v1';
export const objectTypes=['text','rectangle','circle','placeholder','button','divider'];
export const defaultGuides={thirds:false,center:false,margins:true,columns:'none'};
export function normalizeGuides(value){return{thirds:value?.thirds===true,center:value?.center===true,margins:value?.margins!==false,columns:['4','6','12'].includes(value?.columns)?value.columns:'none'};}
const color=(v,fallback)=>/^#[a-f\d]{6}$/i.test(v)?v:fallback;
export function makeObject(type,id){return{id,type,x:60,y:60,width:type==='divider'?360:type==='text'?340:160,height:type==='text'?70:type==='divider'?2:100,rotation:0,fill:type==='text'?'#202820':'#a9ba83',opacity:100,border:0,borderColor:'#34432a',fontSize:28,fontWeight:400,alignment:'left',textColor:'#202820',text:{id:type==='button'?'Lihat pameran':'Ruang untuk Ide',en:type==='button'?'Visit exhibition':'Room for Ideas'}};}
export function initialCanvas(){return{version:1,objects:[{...makeObject('text','title'),x:40,y:40,fontSize:38,fontWeight:700},{...makeObject('placeholder','image'),x:40,y:135,width:400,height:180},{...makeObject('text','details'),x:40,y:340,fontSize:20,text:{id:'24 OKT · Studio 02',en:'24 OCT · Studio 02'}},{...makeObject('button','cta'),x:40,y:420,width:210,height:50,fontSize:18,fill:'#34432a',textColor:'#ffffff'}]};}
export function sanitizeCanvas(input){if(input?.version!==1||!Array.isArray(input.objects))return initialCanvas();const seen=new Set();return{version:1,objects:input.objects.slice(0,30).filter(o=>o&&objectTypes.includes(o.type)&&typeof o.id==='string'&&!seen.has(o.id)&&seen.add(o.id)).map(o=>{const base=makeObject(o.type,o.id.slice(0,80));return{...base,x:clamp(o.x,0,480),y:clamp(o.y,0,540),width:clamp(o.width,12,480),height:clamp(o.height,2,540),rotation:clamp(o.rotation,-180,180),opacity:clamp(o.opacity,0,100),border:clamp(o.border,0,12),fontSize:clamp(o.fontSize,10,100),fontWeight:clamp(o.fontWeight,100,900),fill:color(o.fill,base.fill),borderColor:color(o.borderColor,base.borderColor),textColor:color(o.textColor,base.textColor),alignment:['left','center','right'].includes(o.alignment)?o.alignment:'left',text:{id:typeof o.text?.id==='string'?o.text.id.slice(0,500):base.text.id,en:typeof o.text?.en==='string'?o.text.en.slice(0,500):base.text.en}};})};}
export function readCanvas(raw){try{return sanitizeCanvas(JSON.parse(raw));}catch{return initialCanvas();}}
export function commitHistory(history,next){if(JSON.stringify(history.present)===JSON.stringify(next))return history;return{past:[...history.past,history.present].slice(-40),present:next,future:[]};}
export function undoHistory(h){return h.past.length?{past:h.past.slice(0,-1),present:h.past.at(-1),future:[h.present,...h.future].slice(0,40)}:h;}
export function redoHistory(h){return h.future.length?{past:[...h.past,h.present].slice(-40),present:h.future[0],future:h.future.slice(1)}:h;}
export function analyzeCanvas(canvas){const objects=canvas.objects.filter(o=>o.opacity>20),texts=objects.filter(o=>o.type==='text'),notes=[];if(texts.length>1){const sizes=texts.map(o=>o.fontSize);if(Math.max(...sizes)/Math.min(...sizes)<1.3)notes.push('obsHierarchy');const sorted=[...texts].sort((a,b)=>a.y-b.y),gaps=sorted.slice(1).map((o,i)=>o.y-sorted[i].y-sorted[i].height);if(gaps.length>1&&Math.max(...gaps)-Math.min(...gaps)>12)notes.push('obsSpacing');}const areas=objects.filter(o=>o.type!=='divider').map(o=>o.width*o.height).sort((a,b)=>b-a);if(areas.length>1&&areas[0]/areas[1]>2)notes.push('obsFocus');const attention=objects.filter(o=>o.width*o.height>12000&&contrastRatio(o.fill,'#eceee5')>3);if(attention.length>=3)notes.push('obsCompetition');if(objects.some(o=>o.type==='button'&&contrastRatio(o.textColor,o.fill)<4.5))notes.push('obsCTA');return notes.length?notes:['obsClear'];}
