import { bi, sourceLinks } from '../shared.js';
const rows = [
  ['proximity','Proximity','Kedekatan','Elemen berdekatan sering terlihat sebagai satu kelompok.','Nearby elements often appear as one group.','proximity','Dekatkan detail ke judul terkait, lalu tambah jarak antarsesi.','Place details near their related title, then increase gaps between sessions.','Jarak yang sama membuat hubungan tiap kelompok kurang jelas.','Equal spacing makes group relationships less clear.'],
  ['similarity','Similarity','Kesamaan','Bentuk, warna, atau ukuran yang sama dapat terasa berhubungan.','Shapes, colors or sizes that match can feel related.','similarity','Beri bentuk sama untuk peran yang sama, lalu coba warna sebagai petunjuk tambahan.','Use matching shapes for matching roles, then try color as an additional cue.','Warna sama dipakai untuk kategori berbeda tanpa alasan.','The same color is used for different categories without a reason.'],
  ['closure','Closure','Penutupan','Mata sering melengkapi bentuk yang sebagian terputus.','The eye often completes a partially missing shape.','closure','Buat lingkaran terputus. Ubah besar celah dan amati kapan bentuknya sulit dikenali.','Create a broken circle. Adjust the gap and observe when recognition becomes difficult.','Terlalu banyak bagian hilang membuat simbol sulit dikenali.','Too much missing information makes a symbol hard to recognize.'],
  ['continuity','Continuity','Kesinambungan','Mata cenderung mengikuti jalur atau garis yang berlanjut.','The eye tends to follow a continuing path or line.','continuity','Susun titik mengikuti kurva, lalu geser beberapa titik menjauh dari jalur.','Arrange dots along a curve, then move a few away from the path.','Alur dekoratif mengarahkan mata menjauh dari informasi.','A decorative path leads the eye away from information.'],
  ['figure-ground','Figure–ground','Objek dan latar','Kita membedakan objek yang diamati dari area latarnya.','We distinguish the observed object from its background.','figure','Ubah kontras objek dengan latar tanpa mengubah bentuknya.','Change the contrast between object and background without changing its shape.','Nilai objek dan latar terlalu mirip untuk tugas membaca cepat.','Object and background values are too similar for quick recognition.'],
  ['common-region','Common region','Area bersama','Elemen dalam satu area pembatas sering terlihat satu kelompok.','Elements within one boundary often appear as a group.','region','Tambahkan area halus di belakang satu kelompok bentuk, lalu hilangkan lagi.','Add a subtle bounded area behind one group of shapes, then remove it.','Batas area tidak sesuai dengan hubungan informasi.','Area boundaries do not match information relationships.'],
  ['connectedness','Connectedness','Keterhubungan','Garis penghubung dapat membuat dua elemen terasa berkaitan.','A connecting line can make two elements feel related.','connected','Hubungkan pasangan bentuk dengan garis. Coba pasangan yang berjauhan.','Connect paired shapes with lines. Try pairs that are far apart.','Terlalu banyak garis bersilangan mengaburkan pasangan.','Too many crossing lines obscure the pairs.'],
  ['common-fate','Common fate','Gerak bersama','Elemen yang bergerak searah sering dianggap satu kelompok.','Elements moving in the same direction often appear as one group.','fate','Bandingkan dua arah gerak. Gunakan tombol putar; pada reduced motion, amati panah arah.','Compare two movement directions. Use play; with reduced motion, inspect the direction arrows.','Gerak tanpa fungsi mengganggu pesan dan kenyamanan.','Purposeless movement distracts from the message and reduces comfort.']
];
export const gestaltTopics = rows.map(([slug,en,id,definitionID,definitionEN,experiment,taskID,taskEN,mistakeID,mistakeEN])=>({
  slug:`gestalt/${slug}`, title:bi(`${en} · ${id}`,en), category:'perception', difficulty:'beginner', experiment, color:'#d9ff68',
  shortDefinition:bi(definitionID,definitionEN), explanation:bi(taskID,taskEN),
  whyItMatters:bi('Petunjuk ini membantu pembaca menemukan hubungan visual dalam poster dan infografik.','This cue helps viewers find visual relationships in posters and infographics.'),
  deepDive:bi('Bandingkan petunjuk ini dengan proximity dan similarity. Bila petunjuk saling bersaing, periksa mana yang paling sesuai dengan hubungan informasi. Ini kecenderungan persepsi, bukan hukum untuk semua konteks.','Compare this cue with proximity and similarity. When cues compete, check which best matches the information relationships. This is a perceptual tendency, not a law for every context.'),
  aliases:[slug,en,id], keywords:['gestalt',slug,en,id,'grouping','pengelompokan'],related:['gestalt','figure-ground','alignment'],
  control:bi('Kekuatan petunjuk','Cue strength'),weak:bi('Petunjuk hubungan kurang terlihat.','The relationship cue is less visible.'),strong:bi('Petunjuk hubungan lebih mudah dikenali.','The relationship cue is easier to recognize.'),
  examples:[{weak:bi('Petunjuk kurang terlihat.','Less visible cue.'),strong:bi('Petunjuk lebih jelas.','Clearer cue.')}],
  commonMistakes:[bi(mistakeID,mistakeEN)],tryItYourself:bi(taskID,taskEN),
  reflectionQuestions:[bi('Apa yang berubah dalam kelompok yang kamu lihat? Jelaskan petunjuknya.','What changes in the groups you perceive? Explain the cue.')],
  keyTakeaway:bi(definitionID,definitionEN),source:sourceLinks.gestalt
}));
