import { bi } from './shared.js';
export const ui = {
  home:bi('Beranda','Home'),explore:bi('Jelajah','Explore'),theory:bi('Teori','Theory'),playground:bi('Playground','Playground'),challenges:bi('Tantangan','Challenges'),reference:bi('Referensi cepat','Quick reference'),glossary:bi('Glosarium','Glossary'),
  search:bi('Cari teori','Search theories'),searchHint:bi('Coba “desain terlihat ramai”','Try “my design looks crowded”'),searchPlaceholder:bi('Teori, istilah, atau masalah desain…','Theory, term, or design problem…'),noResults:bi('Tidak ditemukan. Coba kata “ruang”, “warna”, atau “hierarki”.','No matches. Try “space”, “color”, or “hierarchy”.'),close:bi('Tutup','Close'),menu:bi('Menu','Menu'),language:bi('Bahasa','Language'),
  tagline:bi('Lihat mengapa desain bekerja.','See why design works.'),homeTitle:bi('Belajar desain, lewat apa yang kamu lihat.','Learn design through what you see.'),homeIntro:bi('Amati. Bandingkan. Ubah satu hal. Temukan alasan di balik keputusan visual.','Observe. Compare. Change one thing. Discover the reasoning behind visual decisions.'),atlas:bi('Atlas teori','Theory atlas'),all:bi('Semua','All'),topics:bi('topik','topics'),districts:bi('distrik','districts'),openLesson:bi('Buka pelajaran','Open lesson'),begin:bi('Mulai eksplorasi','Start exploring'),continue:bi('Lanjut belajar','Continue learning'),
  quick:bi('Ringkas','Quick'),learn:bi('Pelajari','Learn'),deep:bi('Lebih dalam','Deep dive'),why:bi('Mengapa penting?','Why does it matter?'),experiment:bi('Eksperimen visual','Visual experiment'),experimentHint:bi('Ubah satu variabel, lalu perhatikan apa yang berbeda.','Change one variable, then notice what differs.'),compare:bi('Bandingkan dua pendekatan','Compare two approaches'),weak:bi('Petunjuk kurang jelas','Less clear cues'),strong:bi('Petunjuk lebih jelas','Clearer cues'),contextNote:bi('Contoh untuk konteks ini. Pilihan terbaik bergantung pada pesan dan audiens.','Examples for this context. The best choice depends on the message and audience.'),mistakes:bi('Kesalahan yang sering terjadi','Common mistakes'),try:bi('Coba di karya sendiri','Try it in your own design'),reflect:bi('Refleksi siswa','Student reflection'),related:bi('Teori terkait','Related theories'),takeaway:bi('Hal yang perlu diingat','Key takeaway'),sources:bi('Sumber & bacaan','Sources & reading'),sourceDate:bi('Rujukan diperiksa 1 Oktober 2026. Eksperimen dan brief dibuat khusus untuk belajar.','References checked 1 October 2026. Experiments and briefs were made for learning.'),
  bookmark:bi('Simpan','Bookmark'),bookmarked:bi('Tersimpan','Bookmarked'),complete:bi('Tandai dipelajari','Mark as learned'),completed:bi('Sudah dipelajari','Learned'),progress:bi('Progres belajar','Learning progress'),storage:bi('Tersimpan di browser perangkat ini.','Saved in this browser on this device.'),storageError:bi('Penyimpanan tidak tersedia. Preferensi dan progres berlaku selama sesi ini.','Storage is unavailable. Preferences and progress last for this session.'),beginner:bi('Pemula · Kelas 9–12','Beginner · Grades 9–12'),reset:bi('Atur ulang','Reset'),before:bi('Sebelum','Before'),after:bi('Sesudah','After'),
  mapTitle:bi('Satu kota, banyak cara melihat.','One city, many ways to see.'),mapIntro:bi('Pilih distrik di peta atau daftar kategori. Setiap distrik menghubungkan prinsip yang saling mendukung.','Choose a district on the map or in the category list. Each district connects principles that support each other.'),mapHint:bi('Geser untuk memutar · Scroll untuk zoom · Pilih distrik','Drag to orbit · Scroll to zoom · Select a district'),mapFallback:bi('Peta 3D tidak tersedia. Semua materi tetap dapat dibuka dari daftar distrik.','The 3D map is unavailable. All lessons remain accessible through the district list.'),mapLoading:bi('Menyiapkan kota teori…','Preparing the theory city…'),fullscreen:bi('Perluas peta','Expand map'),exitFullscreen:bi('Kembali ke ukuran biasa','Exit expanded view'),fullscreenFallback:bi('Peta diperluas di jendela ini. Tekan Esc untuk kembali.','Map expanded in this window. Press Escape to return.'),
  playgroundTitle:bi('Ubah satu hal. Lihat pengaruhnya.','Change one thing. See its effect.'),playgroundIntro:bi('Pilih prinsip, ubah kontrolnya, lalu bandingkan dengan titik awal. Tidak ada nilai otomatis: jelaskan keputusanmu.','Choose a principle, adjust its control, then compare with the starting point. There is no automatic score: explain your decision.'),selectTheory:bi('Pilih prinsip','Choose a principle'),snapshot:bi('Simpan pembanding','Save comparison'),snapshotSaved:bi('Pembanding tersimpan untuk sesi ini.','Comparison saved for this session.'),current:bi('Eksperimen saat ini','Current experiment'),baseline:bi('Pembanding','Comparison'),
  challengesTitle:bi('Jadi detektif desain.','Become a design detective.'),challengesIntro:bi('Amati contoh, pilih alasan yang paling sesuai, dan baca pembahasannya.','Observe an example, choose the best explanation, and read the feedback.'),answer:bi('Pilih satu jawaban.','Choose one answer.'),correct:bi('Tepat.','Correct.'),incorrect:bi('Belum tepat.','Not quite.'),retry:bi('Ulangi tantangan','Retry challenge'),challengeDone:bi('Tantangan selesai','Challenge complete'),question:bi('Soal','Question'),detective:bi('Detektif desain','Design detective'),
  referenceIntro:bi('Dua puluh prinsip dalam satu lembar panduan. Pilih topik untuk melihat eksperimennya.','Twenty principles in one guide. Choose a topic to see its experiment.'),print:bi('Cetak panduan','Print guide'),bookmarks:bi('Hanya tersimpan','Bookmarks only'),noBookmarks:bi('Belum ada topik tersimpan. Gunakan tombol Simpan pada pelajaran.','No bookmarks yet. Use Bookmark on a lesson.'),glossaryIntro:bi('Istilah singkat untuk membantu membahas keputusan visual.','Short terms to help discuss visual decisions.'),
  subtopics:bi('Delapan petunjuk Gestalt','Eight Gestalt cues'),toolNote:bi('Latihan dilakukan mandiri di aplikasi pilihanmu. Tidak diperlukan koneksi akun.','Practice independently in your chosen app. No account connection is needed.'),canvaStep:bi('Buat dua salinan halaman di Canva. Terapkan perubahan pada bentuk atau teks di versi kedua. Bandingkan pada ukuran tampil sebenarnya.','Create two page copies in Canva. Apply the change to shapes or text in the second version. Compare at the actual display size.'),figmaStep:bi('Duplikasikan frame di Figma. Ubah properti layer yang terkait, gunakan guides atau auto layout jika membantu, lalu bandingkan kedua frame.','Duplicate a frame in Figma. Change the relevant layer property, use guides or auto layout when useful, then compare both frames.'),
  footer:bi('Amati hubungan. Jelaskan keputusan.','Observe relationships. Explain decisions.'),notFound:bi('Halaman tidak ditemukan','Page not found'),backHome:bi('Kembali ke beranda','Back to home'),play:bi('Putar gerak','Play motion'),pause:bi('Jeda gerak','Pause motion'),motionNote:bi('Panah menunjukkan arah; gerak dihentikan bila reduced motion aktif.','Arrows show direction; motion is stopped when reduced motion is enabled.'),
  searchCount:bi('hasil','results'),savedTopics:bi('topik dipelajari','topics learned'),guideNote:bi('Teori desain adalah panduan untuk diuji dalam konteks, bukan hukum universal.','Design theories are guidelines to test in context, not universal laws.')
};
