'use client';
import dynamic from 'next/dynamic';
import {useEffect,useRef,useState} from 'react';
import {useLearning} from './LearningProvider';
import {categories} from '../content/shared';
import Icon from './InterfaceIcon';
const TheoryCity=dynamic(()=>import('./scene/TheoryCity'),{ssr:false});
export default function MapExplorer({selected,onSelect}){const {t,l}=useLearning();const ref=useRef(),toggle=useRef();const [reset,setReset]=useState(0),[mode,setMode]=useState(null),[notice,setNotice]=useState('');const expanded=mode!==null;
  useEffect(()=>{const sync=()=>{if(document.fullscreenElement===ref.current)setMode('native');else setMode(current=>current==='native'?null:current);};document.addEventListener('fullscreenchange',sync);return()=>document.removeEventListener('fullscreenchange',sync);},[]);
  useEffect(()=>{if(mode!=='fallback')return;const previous=document.activeElement;const container=ref.current;const hidden=[];let branch=container;while(branch&&branch!==document.body){for(const sibling of branch.parentElement?.children||[])if(sibling!==branch){hidden.push([sibling,sibling.hasAttribute('inert')]);sibling.setAttribute('inert','');}branch=branch.parentElement;}toggle.current?.focus();const keys=event=>{if(event.key==='Escape'){event.preventDefault();setMode(null);}if(event.key==='Tab'){const items=[...container.querySelectorAll('button:not(:disabled)')];const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};document.addEventListener('keydown',keys);return()=>{hidden.forEach(([element,hadInert])=>{if(!hadInert)element.removeAttribute('inert');});document.removeEventListener('keydown',keys);previous?.focus?.({preventScroll:true});};},[mode]);
  const fullscreen=async()=>{setNotice('');if(document.fullscreenElement===ref.current){await document.exitFullscreen();return;}if(expanded){setMode(null);return;}try{if(!ref.current.requestFullscreen||!document.fullscreenEnabled)throw new Error('Unavailable');await ref.current.requestFullscreen();}catch{setMode('fallback');setNotice('fallback');}};
  return <div className={`map-explorer ${expanded?'map-expanded':''}`} ref={ref} role={mode==='fallback'?'dialog':undefined} aria-modal={mode==='fallback'?true:undefined} aria-label={t('explore')}><div className="map-toolbar"><span><Icon name="city" size={18}/> DESIGN THEORY CITY</span><div><button onClick={()=>setReset(value=>value+1)}><Icon name="compass" size={16}/>{t('reset')}</button><button ref={toggle} onClick={fullscreen}><Icon name={expanded?'minimize':'maximize'} size={16}/>{t(expanded?'exitFullscreen':'fullscreen')}</button></div></div><div className="map-canvas"><TheoryCity selected={selected} onSelect={onSelect} resetKey={reset} labels={Object.fromEntries(categories.map(item=>[item.id,l(item.title)]))} fallback={t('mapFallback')}/></div><div className="map-bottom"><p>{t('mapHint')}</p>{expanded&&<div className="map-district-controls">{categories.map(item=><button key={item.id} aria-pressed={selected===item.id} onClick={()=>onSelect(item.id)}>{l(item.title)}</button>)}</div>}</div>{notice&&<p className="caption" role="status">{t('fullscreenFallback')}</p>}</div>;
}
