'use client';
import {useEffect,useRef,useState} from 'react';
import {useLearning} from './LearningProvider';
import {Choice,ColorInput,Toggle} from './labs/Controls';
import {STORAGE_KEY,defaultGuides,normalizeGuides,objectTypes,makeObject,initialCanvas,sanitizeCanvas,readCanvas,commitHistory,undoHistory,redoHistory,analyzeCanvas} from '../lib/playground';
function Numeric({name,value,onChange,min=0,max=540}){return <label className="editor-number"><span>{name}</span><input type="number" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;}
function ObjectDrawing({o,l}){const common={fill:o.fill,stroke:o.borderColor,strokeWidth:o.border};const tx=o.alignment==='center'?o.width/2:o.alignment==='right'?o.width:0,anchor=o.alignment==='center'?'middle':o.alignment==='right'?'end':'start';return <>{o.type==='text'?<foreignObject width={o.width} height={o.height}><div xmlns="http://www.w3.org/1999/xhtml" style={{color:o.fill,fontSize:o.fontSize,fontWeight:o.fontWeight,textAlign:o.alignment,lineHeight:1.15,overflowWrap:'anywhere',height:'100%',overflow:'hidden'}}>{l(o.text)}</div></foreignObject>:o.type==='circle'?<ellipse cx={o.width/2} cy={o.height/2} rx={o.width/2} ry={o.height/2} {...common}/>:<rect width={o.width} height={o.height} {...common}/>} {o.type==='placeholder'&&<><path d={`M0 ${o.height} L${o.width*.35} ${o.height*.35} L${o.width*.6} ${o.height*.7} L${o.width*.8} ${o.height*.45} L${o.width} ${o.height}`} fill="none" stroke={o.borderColor} strokeWidth="2"/><circle cx={o.width*.78} cy={o.height*.2} r={Math.min(o.width,o.height)*.08} fill={o.borderColor}/></>}{o.type==='button'&&<text x={o.alignment==='left'?12:o.alignment==='right'?o.width-12:tx} y={o.height/2} dominantBaseline="middle" textAnchor={anchor} fill={o.textColor} fontSize={o.fontSize} fontWeight={o.fontWeight}>{l(o.text)}</text>}</>;}
export default function Playground(){const {t,l,language}=useLearning();const [history,setHistory]=useState(()=>({past:[],present:initialCanvas(),future:[]})),[selected,setSelected]=useState('title'),[type,setType]=useState('text'),[guide,setGuide]=useState(defaultGuides),[ready,setReady]=useState(false),[storageOK,setStorageOK]=useState(true),[analyzed,setAnalyzed]=useState(false),[draft,setDraft]=useState(null);const drag=useRef(null),svgRef=useRef(null);const canvas=draft||history.present,object=canvas.objects.find(o=>o.id===selected);
  useEffect(()=>{const frame=requestAnimationFrame(()=>{let saved;try{saved=localStorage.getItem(STORAGE_KEY);}catch{setStorageOK(false);}if(saved){setHistory({past:[],present:readCanvas(saved),future:[]});try{setGuide(normalizeGuides(JSON.parse(saved).guides));}catch{setGuide(defaultGuides);}}setReady(true);});return()=>cancelAnimationFrame(frame);},[]);
  useEffect(()=>{if(!ready)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify({...history.present,guides:guide}));}catch{const frame=requestAnimationFrame(()=>setStorageOK(false));return()=>cancelAnimationFrame(frame);}},[history.present,ready,guide]);
  const commit=next=>{setHistory(old=>commitHistory(old,sanitizeCanvas(next)));setAnalyzed(false);};
  const patch=(key,value)=>commit({...canvas,objects:canvas.objects.map(o=>o.id===selected?{...o,[key]:value}:o)});
  const add=()=>{if(canvas.objects.length>=30)return;const id=`object-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;commit({...canvas,objects:[...canvas.objects,{...makeObject(type,id),x:40+(canvas.objects.length%6)*20,y:40+(canvas.objects.length%6)*20}]});setSelected(id);};
  const duplicate=()=>{if(!object||canvas.objects.length>=30)return;const id=`copy-${Date.now()}`;commit({...canvas,objects:[...canvas.objects,{...object,id,x:object.x+15,y:object.y+15}]});setSelected(id);};
  const point=e=>{const p=svgRef.current.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svgRef.current.getScreenCTM().inverse());};
  const start=(e,o,resize=false)=>{e.preventDefault();e.stopPropagation();setSelected(o.id);e.currentTarget.setPointerCapture(e.pointerId);drag.current={id:o.id,resize,pointerId:e.pointerId,point:point(e),base:canvas};};
  const pendingDrag=useRef(null);
  const move=e=>{const d=drag.current;if(!d||d.pointerId!==e.pointerId)return;const p=point(e),dx=p.x-d.point.x,dy=p.y-d.point.y;const next=sanitizeCanvas({...d.base,objects:d.base.objects.map(o=>{if(o.id!==d.id)return o;const angle=o.rotation*Math.PI/180;return{...o,...(d.resize?{width:Math.round(o.width+dx*Math.cos(angle)+dy*Math.sin(angle)),height:Math.round(o.height-dx*Math.sin(angle)+dy*Math.cos(angle))}:{x:Math.round(o.x+dx),y:Math.round(o.y+dy)})};})});pendingDrag.current=next;setDraft(next);};
  const finish=e=>{if(!drag.current||drag.current.pointerId!==e.pointerId)return;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(pendingDrag.current)commit(pendingDrag.current);pendingDrag.current=null;setDraft(null);drag.current=null;};
  const keyboard=(e,o)=>{const delta=e.shiftKey?10:1;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();setSelected(o.id);commit({...canvas,objects:canvas.objects.map(item=>item.id===o.id?{...item,x:item.x+(e.key==='ArrowLeft'?-delta:e.key==='ArrowRight'?delta:0),y:item.y+(e.key==='ArrowUp'?-delta:e.key==='ArrowDown'?delta:0)}:item)});}if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(o.id);}};
  const layer=value=>{const next=[...canvas.objects],index=next.findIndex(o=>o.id===selected),[item]=next.splice(index,1);next.splice(Math.max(0,Math.min(next.length,value-1)),0,item);commit({...canvas,objects:next});};
  return <><div className="page-intro"><p className="eyebrow">DESIGN WORKBENCH / 01</p><h1>{t('editorTitle')}</h1><p>{t('editorIntro')}</p></div><div className="editor-toolbar"><Choice name={t('add')} value={type} onChange={setType} options={objectTypes.map(k=>[k,t(k)])}/><button className="primary-button" disabled={!ready||canvas.objects.length>=30} onClick={add}>+ {t('add')}</button><button className="outline-button" disabled={!object||canvas.objects.length>=30} onClick={duplicate}>{t('duplicate')}</button><button className="outline-button" disabled={!object} onClick={()=>{commit({...canvas,objects:canvas.objects.filter(o=>o.id!==selected)});setSelected(null);}}>{t('delete')}</button><button className="outline-button" disabled={!history.past.length} onClick={()=>{setHistory(undoHistory);setAnalyzed(false);}}>{t('undo')}</button><button className="outline-button" disabled={!history.future.length} onClick={()=>{setHistory(redoHistory);setAnalyzed(false);}}>{t('redo')}</button><button className="outline-button" onClick={()=>{commit(initialCanvas());setSelected('title');setGuide(defaultGuides);}}>{t('reset')}</button></div>
  <div className="editor-workspace"><aside className="editor-objects"><h2>{t('objects')}</h2>{canvas.objects.map((o,i)=><button key={o.id} aria-pressed={selected===o.id} onClick={()=>setSelected(o.id)}><span>{String(i+1).padStart(2,'0')}</span> {t(o.type)}</button>)}{!canvas.objects.length&&<p>{t('emptyCanvas')}</p>}<div className="editor-guides"><h3>{t('guides')}</h3>{['thirds','center','margins'].map(key=><Toggle key={key} name={t(key==='center'?'centerLines':key)} value={guide[key]} onChange={v=>setGuide(old=>({...old,[key]:v}))}/>)}<Choice name={t('grid')} value={guide.columns} onChange={v=>setGuide(old=>({...old,columns:v}))} options={['none','4','6','12'].map(key=>[key,key==='none'?t('off'):t(`grid${key}`)])}/></div></aside>
  <div className="editor-stage"><svg ref={svgRef} className="editor-canvas" viewBox="0 0 480 540" aria-label={t('playground')} onPointerMove={move} onPointerUp={finish} onPointerCancel={()=>{setDraft(null);pendingDrag.current=null;drag.current=null;}}><rect width="480" height="540" fill="#eceee5"/>{canvas.objects.map(o=><g key={o.id} transform={`translate(${o.x} ${o.y}) rotate(${o.rotation} ${o.width/2} ${o.height/2})`} opacity={o.opacity/100} tabIndex="0" role="button" aria-label={`${t(o.type)}: ${l(o.text)}`} aria-pressed={selected===o.id} onKeyDown={e=>keyboard(e,o)} onPointerDown={e=>start(e,o)} onClick={()=>setSelected(o.id)}><ObjectDrawing o={o} l={l}/><rect width={o.width} height={o.height} fill="transparent" stroke={selected===o.id?'#326fbc':'none'} strokeWidth="2"/>{selected===o.id&&<rect x={o.width-6} y={o.height-6} width="12" height="12" fill="#326fbc" stroke="#ffffff" strokeWidth="1" onPointerDown={e=>start(e,o,true)} aria-label={t('resizeHint')}/>}</g>)}<g className="editor-overlays" stroke="#bd6440" fill="none" strokeDasharray="4 4" opacity=".7" pointerEvents="none">{guide.thirds&&[1,2].map(i=><path key={i} d={`M${480*i/3} 0 V540 M0 ${540*i/3} H480`}/>)}{guide.center&&<path d="M240 0 V540 M0 270 H480"/>}{guide.margins&&<rect x="30" y="30" width="420" height="480"/>}{guide.columns!=='none'&&Array.from({length:Number(guide.columns)},(_,i)=><rect key={i} x={30+i*420/Number(guide.columns)} y="0" width={420/Number(guide.columns)-8} height="540" fill="#bd644011"/>)}</g></svg><p className="caption">{t('moveHint')}<br/>{t('resizeHint')}</p></div>
  <aside className="editor-inspector"><h2>{t('inspector')}</h2>{object?<><div className="editor-number-grid">{[['x','X',0,480],['y','Y',0,540],['width',t('width'),12,480],['height',t('height'),2,540],['rotation',t('rotation'),-180,180],['opacity',t('opacity'),0,100],['border',t('border'),0,12]].map(([key,name,min,max])=><Numeric key={key} name={name} value={object[key]} min={min} max={max} onChange={v=>patch(key,v)}/>)}</div><ColorInput name={t('fill')} value={object.fill} onChange={v=>patch('fill',v)}/><ColorInput name={t('borderColor')} value={object.borderColor} onChange={v=>patch('borderColor',v)}/>{['text','button'].includes(object.type)&&<><label className="lab-control"><span>{t('text')}</span><textarea value={l(object.text)} maxLength={500} onChange={e=>patch('text',{...object.text,[language]:e.target.value})}/></label><p className="caption">{t('textEdits')}</p><Numeric name={t('fontSize')} value={object.fontSize} min={10} max={100} onChange={v=>patch('fontSize',v)}/><Numeric name={t('fontWeight')} value={object.fontWeight} min={100} max={900} onChange={v=>patch('fontWeight',v)}/><Choice name={t('alignment')} value={object.alignment} onChange={v=>patch('alignment',v)} options={['left','center','right'].map(key=>[key,t(key)])}/>{object.type==='button'&&<ColorInput name={t('text')} value={object.textColor} onChange={v=>patch('textColor',v)}/>}</>}<Numeric name={t('layer')} value={canvas.objects.findIndex(o=>o.id===selected)+1} min={1} max={canvas.objects.length} onChange={layer}/></>:<p>{t('selectObject')}</p>}</aside></div>
  <div className="editor-analysis"><button className="primary-button" onClick={()=>setAnalyzed(true)}>{t('analyze')} ↗</button><p className="caption" role="status">{t(storageOK?'savedLocal':'storageFailed')}</p><p className="caption">{t('objectLimit')}</p>{analyzed&&<section aria-live="polite"><h2>{t('observations')}</h2><ul>{analyzeCanvas(canvas).map(key=><li key={key}>{t(key)}</li>)}</ul><p className="caption">{t('analysisLimit')}</p></section>}</div></>;
}
