'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useLearning} from './LearningProvider';
import {referenceCards} from '../content/reference';
import {categories,sourceLinks} from '../content/shared';
import {theories} from '../content/theories/index';
import {glossary} from '../content/glossary';
export function Reference(){const {t,l}=useLearning();const [checked,setChecked]=useState([]);return <><div className="page-intro page-intro-actions"><div><p className="eyebrow">{t('reference')}</p><h1>{t('referenceChecklist')}</h1><p>{t('referenceHelp')}</p></div><div className="reference-actions"><button className="outline-button" onClick={()=>setChecked([])}>{t('resetChecks')}</button><button className="outline-button" onClick={()=>window.print()}>{t('print')}</button></div></div><div className="reference-checklists">{referenceCards.map(card=><section key={card.id}><div className="checklist-heading"><h2>{l(card.title)}</h2><span>{checked.filter(key=>key.startsWith(`${card.id}:`)).length} / {card.checks.length}</span></div><fieldset><legend>{t('askYourself')}</legend>{card.checks.map((copy,i)=>{const key=`${card.id}:${i}`;return <label key={key}><input type="checkbox" checked={checked.includes(key)} onChange={()=>setChecked(old=>old.includes(key)?old.filter(value=>value!==key):[...old,key])}/><span>{l(copy)}</span></label>;})}</fieldset><Link className="text-link" href={`/theory/${card.theory}/`}>{t('openLesson')} ↗</Link></section>)}</div><p className="caption">{checked.length} / 17 · {t('checked')}</p><details className="reference-library"><summary>{t('atlas')} · 20</summary><div className="reference-grid">{categories.map(category=><section key={category.id}><h2 style={{color:category.color}}>{l(category.title)}</h2>{theories.filter(item=>item.category===category.id).map(item=><Link key={item.slug} href={`/theory/${item.slug}/`}><b>{l(item.title)} ↗</b><p>{l(item.shortDefinition)}</p></Link>)}</section>)}</div></details><p className="caption">{t('guideNote')}</p><section className="source-section"><h2>{t('sources')}</h2>{Object.values(sourceLinks).map(source=><a href={source.url} key={source.url} target="_blank" rel="noopener noreferrer">{source.title} ↗</a>)}<a href="https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html" target="_blank" rel="noopener noreferrer">W3C · Contrast (Minimum) ↗</a></section></>;}
export function Glossary(){const {t,l}=useLearning();const [query,setQuery]=useState('');const visible=glossary.filter(item=>`${item.term} ${item.label.id} ${item.label.en} ${item.definition.id} ${item.definition.en}`.toLowerCase().includes(query.toLowerCase()));return <><div className="page-intro"><p className="eyebrow">{t('termLabel')}</p><h1>{t('glossary')}</h1><p>{t('glossaryIntro')}</p></div><label className="library-search"><span className="sr-only">{t('search')}</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder={t('searchPlaceholder')}/></label><dl className="glossary-list">{visible.map(item=><div key={item.term}><dt>{l(item.label)}</dt><dd><p>{l(item.definition)}</p><Link href={`/theory/${item.related}/`}>{t('relatedLesson')} ↗</Link></dd></div>)}</dl>{!visible.length&&<p className="empty-state">{t('noResults')}</p>}</>;}
