'use client';
import {useState} from 'react';
import {useLearning} from './LearningProvider';
import {Choice} from './labs/Controls';
import {activities,detectiveClues,priorityItems} from '../content/learning-ui';
import {contrastRatio} from '../lib/color';
import {initialOrder,movePriority,alignmentPosition,consistentAlignment} from '../lib/activities';
function FocusChoice({choice,onChange}){const {t}=useLearning();return <div className="focus-choice">{Array.from({length:6},(_,i)=><button key={i} aria-label={`${t('objects')} ${String.fromCharCode(65+i)}`} aria-pressed={choice===i} onClick={()=>onChange(i)}><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="48" r={i===2?28:19} fill={i===2?'#d9ff68':'#6d7568'}/></svg><span>{String.fromCharCode(65+i)}</span></button>)}</div>;}
function GestaltChoice({chosen,onChange}){const {t}=useLearning();return <div className="gestalt-choice">{[0,1].map(group=><div key={group}>{Array.from({length:6},(_,j)=>{const i=group*6+j;return <button key={i} aria-label={`${t('objects')} ${i+1}`} aria-pressed={chosen.includes(i)} onClick={()=>onChange(chosen.includes(i)?chosen.filter(v=>v!==i):[...chosen,i])}><span style={{background:j%3===0?'#f5a87e':'#d9ff68'}}/>{i+1}</button>;})}</div>)}</div>;}
export function DetectiveComposition(){const {t}=useLearning();return <svg className="detective-composition" viewBox="0 0 440 420" role="img" aria-label={t('detectivePrompt')}><rect width="440" height="420" fill="#eceee5"/><text x="5" y="46" fontFamily="Georgia" fontSize="29" fill="#26331b">{t('eventName')}</text><circle cx="120" cy="140" r="60" fill="#d4e968"/><circle cx="325" cy="140" r="60" fill="#ed965f"/><text x="65" y="240" fontFamily="Impact" fontSize="22" fill="#26331b">{t('eventDate')}</text><text x="28" y="260" fontFamily="monospace" fontSize="13" fill="#d5d8ce">{t('eventLocation')}</text><text x="190" y="334" fontFamily="Georgia" fontStyle="italic" fontSize="17" fill="#26331b">STUDIO / DESIGN</text><rect x="273" y="358" width="164" height="46" fill="#dae9b4"/><text x="285" y="386" fontSize="15" fill="#26331b">{t('eventCTA')}</text></svg>;}
export default function VisualActivity({activity=activities[0]}){const {t,l,completeActivity,progress}=useLearning();const [choice,setChoice]=useState(null),[chosen,setChosen]=useState([]),[order,setOrder]=useState(initialOrder),[align,setAlign]=useState(['left','right','center']),[revealed,setRevealed]=useState(false);const [checked,setChecked]=useState([]);
  const reset=()=>{setChoice(null);setChosen([]);setOrder(initialOrder);setAlign(['left','right','center']);setChecked([]);setRevealed(false);};const reveal=()=>{setRevealed(true);completeActivity(activity.id);};const {kind}=activity;const ready=kind==='focus'||kind==='color'?choice!==null:kind==='gestalt'?chosen.length>=2:kind==='detective'?checked.length===4:true;
  const ratios=[contrastRatio('#b9bcae','#eceee5'),contrastRatio('#26331b','#eceee5')];
  return <section className="visual-activity"><div className="activity-title"><div><p className="eyebrow">{t('activity')}</p><h2>{l(activity.title)}</h2></div><button className="outline-button" onClick={reset}>{t('reset')}</button></div><p className="activity-prompt">{l(activity.prompt)}</p>
  {kind==='focus'&&<FocusChoice choice={choice} onChange={v=>{setChoice(v);setRevealed(false);}}/>}
  {kind==='gestalt'&&<><p className="caption">{t('chooseObjects')}</p><GestaltChoice chosen={chosen} onChange={v=>{setChosen(v);setRevealed(false);}}/></>}
  {kind==='hierarchy'&&<div className="priority-workspace"><div><p className="caption">{t('priorityHint')}</p><ol className="priority-list">{order.map((id,i)=>{const key=priorityItems.find(item=>item[0]===id)[1];return <li key={id}><span>{t(key)}</span><button disabled={i===0} aria-label={`${t('up')}: ${t(key)}`} onClick={()=>{setOrder(movePriority(order,id,-1));setRevealed(false);}}>↑</button><button disabled={i===order.length-1} aria-label={`${t('down')}: ${t(key)}`} onClick={()=>{setOrder(movePriority(order,id,1));setRevealed(false);}}>↓</button></li>;})}</ol></div><div className="priority-poster" aria-label={t('yourPriority')}>{order.map((id,i)=><p key={id} style={{fontSize:[32,24,20,17,14][i],fontWeight:i===0?700:400}}>{t(priorityItems.find(item=>item[0]===id)[1])}</p>)}</div></div>}
  {kind==='color'&&<><p className="caption">{t('comparisonTask')}</p><div className="color-choice">{ratios.map((ratio,i)=><button key={i} aria-pressed={choice===i} onClick={()=>{setChoice(i);setRevealed(false);}}><span className="color-pair-letter">{i===0?'A':'B'}</span><span className="color-pair-example" style={{color:i===0?'#b9bcae':'#26331b'}}>{t('eventName')}<small>{t('eventLocation')}</small></span>{revealed&&<span className="caption">{t('contrastRatio')}: {ratio.toFixed(2)}:1</span>}</button>)}</div></>}
  {kind==='alignment'&&<div className="alignment-activity"><svg viewBox="0 0 440 280" role="img" aria-label={t('alignmentTask')}><rect width="440" height="280" fill="#eceee5"/>{[36,220,404].map(x=><path key={x} d={`M${x} 20V260`} stroke="#a9b59b" strokeDasharray="3 5"/>)}{[220,290,170].map((w,i)=><rect key={i} x={alignmentPosition(align[i],w)} y={45+i*75} width={w} height={i===0?38:24} fill={['#34432a','#7a9160','#9dac77'][i]}/>)}</svg><div><Choice name={t('alignmentSystem')} value={consistentAlignment(align)?align[0]:'mixed'} onChange={v=>{if(v!=='mixed')setAlign([v,v,v]);setRevealed(false);}} options={[['mixed',t('misalign')],...['left','center','right'].map(key=>[key,t(key)])]}/>{align.map((value,i)=><Choice key={i} name={`${t('objects')} ${i+1}`} value={value} onChange={v=>{setAlign(old=>old.map((mode,j)=>i===j?v:mode));setRevealed(false);}} options={['left','center','right'].map(key=>[key,t(key)])}/>)}</div></div>}
  {kind==='detective'&&<div className="detective-workspace"><DetectiveComposition/><fieldset><legend>{t('fourSelections')}</legend>{detectiveClues.map(clue=><label key={clue.id}><input type="checkbox" checked={checked.includes(clue.id)} disabled={!checked.includes(clue.id)&&checked.length>=4} onChange={()=>{setChecked(old=>old.includes(clue.id)?old.filter(id=>id!==clue.id):[...old,clue.id]);setRevealed(false);}}/><span>{l(clue.label)}</span></label>)}<p className="caption" role="status">{checked.length} / 4</p></fieldset></div>}
  <div className="activity-review"><button className="primary-button" disabled={!ready} onClick={reveal}>{t('reviewObservation')} ↗</button>{progress.completedActivities.includes(activity.id)&&<span className="caption">✓ {t('activityDone')}</span>}</div>{revealed&&<div className="activity-explanation" role="status"><p>{l(activity.explanation)}</p>{kind==='focus'&&<p>{t('attentionReflection')}</p>}{kind==='alignment'&&<p>{t(consistentAlignment(align)?'consistent':'stillExploring')}</p>}{kind==='detective'&&<><h3>{t('detectiveResult')}</h3><ul>{detectiveClues.filter(clue=>checked.includes(clue.id)).map(clue=><li key={clue.id}><b>{l(clue.label)}</b><p>{l(clue.explanation)}</p></li>)}</ul><p>{t('noSingleRedesign')}</p></>}</div>}</section>;
}
