'use client';
import {useState} from 'react';
import {useLearning} from '../LearningProvider';
import {buildPalette,contrastRatio,harmonyColors,harmonyOffsets} from '../../lib/color';
import {Choice,ColorInput,LabFrame,Range} from './Controls';
export default function ColorLab(){const {t}=useLearning();const [h,setH]=useState(30),[s,setS]=useState(65),[light,setLight]=useState(55),[mode,setMode]=useState('complementary'),[palette,setPalette]=useState(()=>buildPalette(30,65,55,'complementary')),[preview,setPreview]=useState('poster');
  const update=(nextH=h,nextS=s,nextL=light,nextMode=mode)=>{setH(nextH);setS(nextS);setLight(nextL);setMode(nextMode);setPalette(buildPalette(nextH,nextS,nextL,nextMode));};const ratio=contrastRatio(palette.text,palette.background);
  return <LabFrame title={t('colorLab')} onReset={()=>{update(30,65,55,'complementary');setPreview('poster');}} controls={<><Range name={t('hue')} value={h} max={359} unit="°" onChange={v=>update(v)}/><Range name={t('saturation')} value={s} onChange={v=>update(h,v)}/><Range name={t('lightness')} value={light} onChange={v=>update(h,s,v)}/><Choice name={t('harmony')} value={mode} onChange={v=>update(h,s,light,v)} options={Object.keys(harmonyOffsets).map(key=>[key,t(key)])}/><h3>{t('paletteRoles')}</h3>{Object.entries(palette).map(([key,value])=><ColorInput key={key} name={t(key)} value={value} onChange={v=>setPalette(old=>({...old,[key]:v}))}/>)}<button className="outline-button" onClick={()=>setPalette(buildPalette(h,s,light,mode))}>{t('resetPalette')}</button></>} footer={<><div className="contrast-readout"><strong>{ratio.toFixed(2)}:1</strong><span>{t('contrastRatio')}</span></div><p>{t('normalText')}: {t(ratio>=4.5?'meets':'below')}<br/>{t('largeText')}: {t(ratio>=3?'meets':'below')}</p><p className="caption">{t('contrastGuidance')}</p><p className="caption">{t('colorMeaning')}</p></>}>
    <div className="harmony-swatches">{harmonyColors(h,s,light,mode).map((color,i)=><span style={{background:color}} key={i}><code>{color}</code></span>)}</div><Choice name={t('preview')} value={preview} onChange={setPreview} options={['poster','social','slide','simpleUI'].map(key=>[key,t(key)])}/><div className={`palette-preview ${preview}`} style={{background:palette.background,color:palette.text,'--palette-primary':palette.primary,'--palette-secondary':palette.secondary,'--palette-accent':palette.accent,'--palette-surface':palette.surface}}><span className="palette-kicker">STUDIO 02 / {t('eventDate')}</span><h3>{t('eventName')}</h3><div className="palette-shapes"><span/><span/></div><p>{t('eventDesc')}</p><span className="palette-cta">{t('eventCTA')} ↗</span>{preview==='simpleUI'&&<div className="palette-surface">{t('eventLocation')}</div>}</div>
  </LabFrame>;
}
