'use client';
import {useState} from 'react';
import {useLearning} from '../LearningProvider';
import {Range,Choice,LabFrame} from './Controls';
import {weakHierarchy,interpolateHierarchy,simulatedOrder} from '../../lib/hierarchy';
export function CompositionPoster({settings}){const {t,language}=useLearning();const align=settings.alignment;const x=align==='left'?32:align==='right'?408:220,anchor=align==='left'?'start':align==='right'?'end':'middle';const gap=settings.spacing;const imgWidth=80+settings.imageScale*1.1;const ctaLight=85-settings.ctaContrast*.65;
  return <svg className="composition-poster" viewBox="0 0 440 440" role="img" aria-label={`${t('sameContent')} — ${t('simulation')}`}><rect width="440" height="440" fill="#eceee5"/><text x={align==='mixed'?95:x} y="50" textAnchor={align==='mixed'?'start':anchor} fill="#666b5b" fontSize="12">{language==='id'?'PAMERAN DESAIN / 2026':'DESIGN EXHIBITION / 2026'}</text><text x={align==='mixed'?220:x} y={90+gap*.2} textAnchor={align==='mixed'?'middle':anchor} fill="#242d1d" fontSize={settings.headlineSize} fontWeight={settings.headlineWeight}>{t('eventName')}</text><rect x={align==='mixed'?170:align==='left'?32:align==='right'?408-imgWidth:220-imgWidth/2} y={112+gap*.3} width={imgWidth} height={70+settings.imageScale*.55} fill="#9dac77"/><path d={`M ${align==='mixed'?195:align==='left'?55:align==='right'?355:195} ${138+gap*.3} l 27 55 38 -38 30 40`} fill="none" stroke="#39472b" strokeWidth="3"/><text x={align==='mixed'?55:x} y={235+gap*.5} textAnchor={align==='mixed'?'start':anchor} fill="#424b3a" fontSize="17">{language==='id'?'Amati. Bereksperimen. Berbagi.':'Observe. Experiment. Share.'}</text><text x={align==='mixed'?300:x} y={270+gap*.45} textAnchor={align==='mixed'?'end':anchor} fill="#747b6c" fontSize="15">{language==='id'?'24 OKT · Studio 02':'24 OCT · Studio 02'}</text><g transform={`translate(${align==='mixed'?160:align==='left'?32:align==='right'?238:135},${292+gap*.6})`}><rect width="170" height="44" fill={`hsl(90 30% ${ctaLight}%)`}/><text x="85" y="28" textAnchor="middle" fill={ctaLight<48?'#f8f8f0':'#555c4d'} fontSize="15" fontWeight="600">{t('eventCTA')}</text></g><text x={align==='mixed'?385:x} y="409" textAnchor={align==='mixed'?'end':anchor} fill="#747b6c" fontSize="12">{t('eventLocation')}</text></svg>;
}
export function HeroExperiment(){const {t}=useLearning();const [value,setValue]=useState(25);return <div className="hero-experiment"><div className="experiment-bar"><span>{t('sameContent')}</span><button onClick={()=>setValue(25)}>{t('reset')} ↺</button></div><CompositionPoster settings={interpolateHierarchy(value)}/><div className="experiment-controls"><Range name={t('beforeAfter')} value={value} onChange={setValue}/><div className="range-endpoints"><span>A · {t('before')}</span><span>B · {t('after')}</span></div><p className="caption">{t('heroObservation')}</p></div></div>;}
export default function HierarchyLab(){const {t}=useLearning();const [settings,setSettings]=useState({...weakHierarchy});const patch=(key,value)=>setSettings(previous=>({...previous,[key]:value}));return <LabFrame title={t('hierarchyLab')} onReset={()=>setSettings({...weakHierarchy})} controls={<><Range name={t('headlineSize')} value={settings.headlineSize} min={20} max={50} unit=" px" onChange={v=>patch('headlineSize',v)}/><Range name={t('headlineWeight')} value={settings.headlineWeight} min={300} max={800} step={100} onChange={v=>patch('headlineWeight',v)}/><Range name={t('imageScale')} value={settings.imageScale} min={20} max={100} onChange={v=>patch('imageScale',v)}/><Range name={t('ctaContrast')} value={settings.ctaContrast} onChange={v=>patch('ctaContrast',v)}/><Range name={t('spacing')} value={settings.spacing} min={4} max={36} unit=" px" onChange={v=>patch('spacing',v)}/><Choice name={t('alignment')} value={settings.alignment} onChange={v=>patch('alignment',v)} options={['mixed','left','center','right'].map(key=>[key,key==='mixed'?t('misalign'):t(key)])}/></>} footer={<div className="hierarchy-order"><h3>{t('viewOrder')}</h3><p className="simulation-label">{t('simulation')}</p><ol>{simulatedOrder(settings).map(item=><li key={item.role}>{t(item.role)}</li>)}</ol><p className="caption">{t('simulationNote')}</p></div>}><CompositionPoster settings={settings}/></LabFrame>;}
