'use client';
import {useState} from 'react';
import {useLearning} from '../LearningProvider';
import {typographyConcepts} from '../../content/lab-ui';
import {Choice,LabFrame,Range} from './Controls';
const initial={family:'Inter',size:28,weight:400,leading:1.5,tracking:0,align:'left',case:'original',width:90};
const pairs=[['equal','equalWeight'],['serif','pairSerif'],['family','pairFamily'],['display','pairDisplay'],['single','pairSingle']];
export default function TypographyLab(){const {t,l,language}=useLearning();const [s,setS]=useState(initial),[edits,setEdits]=useState({}),[pair,setPair]=useState('equal'),[levels,setLevels]=useState({event:22,date:22,location:22,description:22,cta:22});const set=(key,value)=>setS(old=>({...old,[key]:value}));const text=edits[language]??t('typeDefault');
  return <><LabFrame title={t('typeLab')} onReset={()=>{setS(initial);setEdits({});setPair('equal');setLevels({event:22,date:22,location:22,description:22,cta:22});}} controls={<><label className="lab-control"><span>{t('editableText')}</span><textarea value={text} maxLength={500} onChange={e=>setEdits(old=>({...old,[language]:e.target.value}))}/></label><Choice name={t('typeface')} value={s.family} onChange={v=>set('family',v)} options={['Inter','Arial','Georgia','Impact','Verdana'].map(key=>[key,key])}/><Range name={t('fontSize')} value={s.size} min={12} max={64} unit=" px" onChange={v=>set('size',v)}/><Range name={t('fontWeight')} value={s.weight} min={400} max={900} step={100} onChange={v=>set('weight',v)}/><Range name={t('lineHeight')} value={s.leading} min={.8} max={2.5} step={.1} onChange={v=>set('leading',v)}/><Range name={t('tracking')} value={s.tracking} min={-2} max={8} step={.1} unit=" px" onChange={v=>set('tracking',v)}/><Range name={t('textWidth')} value={s.width} min={35} max={100} unit="%" onChange={v=>set('width',v)}/><Choice name={t('alignment')} value={s.align} onChange={v=>set('align',v)} options={['left','center','right'].map(key=>[key,t(key)])}/><Choice name={t('case')} value={s.case} onChange={v=>set('case',v)} options={['original','uppercase','lowercase'].map(key=>[key,t(key==='original'?'originalCase':key)])}/></>} footer={<p>{t('typeObservation')}</p>}><div className="type-specimen"><p style={{fontFamily:s.family==='Inter'?'var(--font-body)':s.family,fontSize:s.size,fontWeight:s.weight,lineHeight:s.leading,letterSpacing:s.tracking,textAlign:s.align,width:`${s.width}%`,textTransform:s.case==='original'?'none':s.case}}>{text}</p></div></LabFrame>
  <section className="type-exercise"><div><h2>{t('hierarchyExercise')}</h2><p className="caption">{t('typeObservation')}</p><Choice name={t('pairing')} value={pair} onChange={setPair} options={pairs.map(([key,label])=>[key,t(label)])}/><p className="caption">{t('pairingGuide')}</p><p className="caption">{t('fontFallback')}</p>{Object.entries(levels).map(([key,value])=><Range key={key} name={t(key)} value={value} min={12} max={54} unit=" px" onChange={v=>setLevels(old=>({...old,[key]:v}))}/>)}</div><div className="type-event">{Object.entries(levels).map(([key,value])=><p key={key} style={{fontSize:value,fontWeight:pair==='equal'?400:pair==='single'?(key==='event'?800:key==='date'?600:400):key==='event'?700:400,fontFamily:pair==='equal'||pair==='single'?'var(--font-body)':pair==='family'?(key==='event'?'Lucida Bright, Georgia':'Lucida Sans, Arial'):key==='event'?(pair==='display'?'Impact':'Georgia'):'var(--font-body)'}}>{key==='event'?t('eventName'):key==='date'?t('eventDate'):key==='location'?t('eventLocation'):key==='description'?t('eventDesc'):t('eventCTA')}</p>)}</div></section><dl className="type-concepts">{typographyConcepts.map(([title,copy],i)=><div key={i}><dt>{l(title)}</dt><dd>{l(copy)}</dd></div>)}</dl></>;
}
