import {chromium,webkit,devices,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {mkdir,writeFile} from 'node:fs/promises';
const origin=process.env.QA_URL||'http://127.0.0.1:3001';
const channel=process.env.QA_BROWSER||'chrome';
const artifacts=new URL('../qa-artifacts/',import.meta.url);await mkdir(artifacts,{recursive:true});
const browser=channel==='webkit'?await webkit.launch({headless:true}):await chromium.launch({channel,headless:true});
const context=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'});
const page=await context.newPage();const errors=[],failedRequests=[],networkFailures=[],consoleDetails=[];const visits=[];let navigating=false;
const observe=screen=>{screen.on('requestfailed',request=>networkFailures.push({url:request.url(),reason:request.failure()?.errorText}));screen.on('pageerror',error=>{errors.push(error.message);consoleDetails.push({text:error.stack,page:screen.url(),navigating});});screen.on('console',message=>{if(message.type()==='error'){errors.push(message.text());consoleDetails.push({text:message.text(),location:message.location(),page:screen.url(),navigating});}});screen.on('response',response=>{if(response.status()>=400)failedRequests.push(`${response.status()} ${response.url()}`);});};observe(page);
const go=async(path,screen=page)=>{navigating=true;try{const response=await screen.goto(origin+path,{waitUntil:'networkidle'});assert.equal(response.status(),200,path);await expect(screen.getByRole('button',{name:'English',exact:true})).toBeEnabled();}finally{navigating=false;}};
try{
  for(const width of [360,390,768,1024,1280,1440]){
    // Each viewport starts independently: resizing a loaded WebKit page and
    // immediately navigating cancels scheduled prefetches in the old document.
    const responsive=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'}),screen=await responsive.newPage();observe(screen);
    for(const path of ['/','/explore/','/theory/visual-hierarchy/','/theory/gestalt/','/theory/color/','/theory/typography/','/playground/','/challenges/','/challenges/design-detective/','/reference/','/glossary/']){
      await go(path,screen);await expect(screen.locator('a[href="/teacher/"]')).toHaveCount(0);const overflow=await screen.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(overflow.scroll<=overflow.width+1,`Horizontal overflow ${width}px ${path}: ${overflow.scroll}`);visits.push({width,path});
    }
    await screen.screenshot({path:fileURLToPath(new URL(`student-${channel}-${width}.png`,artifacts)),fullPage:false});await responsive.close();console.log(`PASS responsive routes: ${width}px`);
  }
  await page.setViewportSize({width:1280,height:900});await go('/challenges/');
  await page.getByRole('button',{name:'English',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('lang','en');
  await page.locator('.focus-choice button').nth(2).click();await page.getByRole('button',{name:'Reveal explanation'}).click();await expect(page.locator('.activity-explanation')).toContainText('Circle C');
  await page.locator('.activity-tabs button').nth(1).click();await page.locator('.gestalt-choice button').nth(0).click();await page.locator('.gestalt-choice button').nth(1).click();await page.getByRole('button',{name:'Reveal explanation'}).click();await expect(page.locator('.activity-explanation')).toContainText('Spacing');
  await page.locator('.activity-tabs button').nth(2).click();await page.getByRole('button',{name:'Move up in priority: 24 OCT 2026',exact:true}).click();await expect(page.locator('.priority-list li').first()).toContainText('24 OCT');await expect(page.locator('.priority-poster p').first()).toHaveText('24 OCT 2026');
  await page.locator('.activity-tabs button').nth(3).click();await page.locator('.color-choice button').nth(1).click();await page.getByRole('button',{name:'Reveal explanation'}).click();await expect(page.locator('.color-choice')).toContainText(':1');
  await page.locator('.activity-tabs button').nth(4).click();await page.getByLabel('Alignment system',{exact:true}).selectOption('center');await page.getByRole('button',{name:'Reveal explanation'}).click();await expect(page.locator('.activity-explanation')).toContainText('one reference line');
  await go('/challenges/design-detective/');await expect(page.getByRole('button',{name:'Reveal explanation'})).toBeDisabled();for(const checkbox of (await page.locator('.detective-workspace input').all()).slice(0,4))await checkbox.check();await expect(page.locator('.detective-workspace input:disabled')).toHaveCount(2);await page.getByRole('button',{name:'Reveal explanation'}).click();await expect(page.locator('.activity-explanation li')).toHaveCount(4);await page.screenshot({path:fileURLToPath(new URL('detective-desktop.png',artifacts)),fullPage:true});
  await go('/reference/');await page.locator('.reference-checklists input').first().check();await page.getByRole('button',{name:'Bahasa Indonesia',exact:true}).click();await expect(page.locator('.reference-checklists input').first()).toBeChecked();await expect(page.getByRole('heading',{name:'Checklist di samping karya'})).toBeVisible();await page.getByRole('button',{name:'Kosongkan checklist'}).click();await expect(page.locator('.reference-checklists input:checked')).toHaveCount(0);
  await go('/glossary/');await page.getByRole('searchbox').fill('Bobot Visual');await expect(page.locator('dl>div')).toHaveCount(1);await expect(page.locator('dt')).toHaveText('Bobot Visual');
  await go('/theory/visual-hierarchy/');await page.getByRole('button',{name:'English',exact:true}).click();const slider=page.locator('.rich-lab input[type=range]').first();await slider.focus();const before=await slider.inputValue();await page.keyboard.press('ArrowRight');assert.notEqual(await slider.inputValue(),before);
  await page.setViewportSize({width:1280,height:900});await go('/playground/');const canvas=page.locator('.editor-canvas'),object=canvas.locator('g[role=button]').first();await object.focus();const xBefore=await page.locator('.editor-number input').first().inputValue();await page.keyboard.press('ArrowRight');await expect(page.locator('.editor-number input').first()).toHaveValue(String(Number(xBefore)+1));await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.editor-number input').first()).toHaveValue(xBefore);
  await page.getByRole('button',{name:'Add',exact:false}).filter({hasText:'+ Add'}).click();await expect(canvas.locator('g[role=button]')).toHaveCount(5);await page.reload({waitUntil:'networkidle'});await expect(canvas.locator('g[role=button]')).toHaveCount(5);
  const selected=canvas.locator('g[role=button]').first();await selected.click();const box=await canvas.boundingBox();const beforeDrag=Number(await page.locator('.editor-number input').first().inputValue());await page.mouse.move(box.x+80*box.width/480,box.y+60*box.height/540);await page.mouse.down();await page.mouse.move(box.x+110*box.width/480,box.y+90*box.height/540,{steps:5});await page.mouse.up();await expect.poll(async()=>Number(await page.locator('.editor-number input').first().inputValue())).toBeGreaterThan(beforeDrag);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.editor-number input').first()).toHaveValue(String(beforeDrag));
  await page.evaluate(()=>localStorage.setItem('design-theory-playground-v1','corrupt'));await page.reload({waitUntil:'networkidle'});await expect(canvas.locator('g[role=button]')).toHaveCount(4);
  await go('/theory/gestalt/common-fate/');await page.getByLabel('Group movement',{exact:true}).check();const animation=await page.locator('.moving-cue').first().evaluate(e=>getComputedStyle(e).animationName);assert.equal(animation,'none');
  const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('design-theory-city:learning-progress:v2')));assert.ok(stored.completedActivities.includes('design-detective-v1'));assert.equal(stored.language,'en');await page.reload({waitUntil:'networkidle'});await expect(page.locator('html')).toHaveAttribute('lang','en');
  assert.equal(await page.evaluate(async()=>('serviceWorker' in navigator?(await navigator.serviceWorker.getRegistrations()).length:0)),0);
  if(channel==='webkit'){const mobile=await browser.newContext({...devices['iPhone 13'],reducedMotion:'reduce'});const screen=await mobile.newPage();observe(screen);for(const path of ['/','/theory/visual-hierarchy/','/challenges/design-detective/','/playground/','/reference/']){await go(path,screen);assert.ok(await screen.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`Mobile WebKit overflow: ${path}`);if(path==='/'){await screen.getByRole('button',{name:'English',exact:true}).tap();}if(path==='/challenges/design-detective/'){for(const checkbox of (await screen.locator('.detective-workspace input').all()).slice(0,4))await checkbox.tap();await screen.getByRole('button',{name:'Reveal explanation'}).tap();await expect(screen.locator('.activity-explanation li')).toHaveCount(4);}if(path==='/playground/'){await screen.getByRole('button',{name:'Add',exact:false}).filter({hasText:'+ Add'}).tap();await expect(screen.locator('.editor-canvas g[role=button]')).toHaveCount(5);}if(path==='/reference/'){await screen.locator('.reference-checklists input').first().tap();await expect(screen.locator('.reference-checklists input').first()).toBeChecked();}}await screen.screenshot({path:fileURLToPath(new URL('mobile-webkit.png',artifacts)),fullPage:false});await mobile.close();}
  assert.deepEqual(errors.slice(0,3),[],'Browser console/runtime errors');assert.deepEqual(failedRequests.slice(0,3),[],'Failed HTTP requests');
  const report={date:'2026-10-02',browser:channel,browserVersion:browser.version(),visits:visits.length,mobileChecks:channel==='webkit'?5:0,widths:[360,390,768,1024,1280,1440],errors,failedRequests,checks:['activities','detective','reference','glossary','student-only navigation','lesson slider keyboard','editor persistence/drag/undo','corrupt storage','reduced motion','language repeat visit','no service worker']};await writeFile(new URL(`report-${channel}.json`,artifacts),JSON.stringify(report,null,2));console.log(`PASS ${channel}: ${visits.length} responsive route checks, learning interactions, keyboard, persistence, recovery, no runtime errors.`);
}catch(error){await page.screenshot({path:fileURLToPath(new URL(`failure-${channel}.png`,artifacts)),fullPage:true}).catch(()=>{});await writeFile(new URL(`failure-${channel}.json`,artifacts),JSON.stringify({url:page.url(),errors,failedRequests,networkFailures,consoleDetails,error:String(error)},null,2));throw error;}finally{await browser.close();}
